name: DBT CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: youfund_dbt

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres  # use dbt-postgres if you use postgres, or your adapter

      - name: Wait for Postgres service (use service container)
        uses: harmon758/postgresql-action@v2.2.0
        with:
          postgresql version: '14'
          postgresql db: 'airflow'
          postgresql user: 'airflow'
          postgresql password: 'airflow'

      - name: dbt deps
        run: dbt deps

      - name: dbt seed (optional, if you have seeds)
        run: dbt seed --profiles-dir . --target dev

      - name: dbt run
        run: dbt run --profiles-dir . --target dev

      - name: dbt test
        run: dbt test --profiles-dir . --target dev
