name: Terraform Provisioning

on:
  push:
    branches:
      - '**'
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'infra/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform on LocalStack'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/tfplan

      - name: Terraform Apply (Manual Approval)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply tfplan
